server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads
spring:
  datasource:
    url: jdbc:mysql://106.14.152.171:3306/cloud?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: cloud
    password: cloud
    max-idle: 10
    min-idle: 5
    test-on-borrow: false
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1
    hikari:
      minimum-idle: 0
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 10000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
redis:
  cache:
    expiration: 3601
ribbon:
  eager-load:
    enabled: true
    clients: panda-auth,panda-user-service
  Httpclient:
    enabled: true
  OkHttp:
    enabled: false
  ReadTimeout: 10000
  ConnectTimeout: 10000

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: false
  httpclient:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
sms:
  tencent-cloud:
    appId: 1400163191
    appKey: 07831d2dacf5878e875199fdb1757c16
oss:
  ali-cloud:
    aliyunDomain: http://oss-cn-hangzhou.aliyuncs.com
    aliyunEndPoint: oss-cn-hangzhou.aliyuncs.com
    aliyunAccessKeyId: LTAIzpgow5PWEhA1
    aliyunAccessKeySecret: kegpx7jujo64ZeqgiWDEfjVk1g6FzV
    aliyunBucketName: bucket-yytour-test
    aliyunPrefix: yycloud